version: '3.9'
services:
  penx_web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXTAUTH_SECRET: adb6e96b7ec73026c7562eff5f8b95ee
        DATABASE_URL: postgres://postgres.xmeeqdwniitxlnofonbc:scW28VJy3aO1Olco@aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres
        NEXT_PUBLIC_DEPLOY_MODE: SELF_HOSTED
        SELF_HOSTED_USERNAME: penx
        SELF_HOSTED_PASSWORD: 123456
    container_name: penx_web
    ports:
      - '3000:3000'
