version: '3'

services:
  penx_web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: penx_web
    environment:
      NEXTAUTH_SECRET: adb6e96b7ec73026c7562eff5f8b95ee
      NEXT_PUBLIC_DEPLOY_MODE: SELF_HOSTED
      SELF_HOSTED_CREDENTIALS: foo_bar/123456
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: penx
      POSTGRES_USER: user
      POSTGRES_PASSWORD: penx
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

volumes:
  postgres_data:
